version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kendarikota
            MYSQL_USER: kendarikota
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 0
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    dbdata:
