version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - mysql-phpmyadmin_mysql_network

networks:
  mysql-phpmyadmin_mysql_network:
    external: true
